version: "3"
services:
   webapi:
      build: 
        context: .
        dockerfile: ./Dockerfile.backend
      ports:
         - "8080:80"
   consoleapp:
      build: 
        context: .
        dockerfile: ./Dockerfile.frontend
