apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
spec:
  selector:
    matchLabels:
      app: webapi
  replicas: 5
  template: 
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: zasmlabs/devcon.webapi:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: webapi
spec:
 type: LoadBalancer
 selector:
   app: webapi
 ports:
   - name: client
     port: 80
     nodePort: 32080
 selector:
   app: webapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consoleclient
spec:
  selector:
    matchLabels:
      app: consoleclient
  replicas: 1
  template: 
    metadata:
      labels:
        app: consoleclient
    spec:
      containers:
      - name: consoleclient
        image: zasmlabs/devcon.consoleclient:latest
        ports:
        - containerPort: 80